name = "custom-url-store"
main = "src/index.ts"
compatibility_date = "2022-10-31"
kv_namespaces = [
  { binding = "URLSTORE", preview_id = "fa060cce2eb24ef69f81d1988c6d6e67", id = "4209bb022c21498d99a0489a241f5f0d" }
]
workers_dev = true